name: mlflow-env
channels:
  - conda-forge
dependencies:
  - python=3.12.7
  - pip>=23.0
  - pip:
      - mlflow==2.19.0
      - cloudpickle==3.1.1
      - numpy==2.3.0
      - pandas==2.3.0
      - scikit-learn==1.5.0
      - scipy==1.11.4
